#!/bin/bash
# Edit RESTaPI.properties to set the REST API server address (RESTaPI-IPAddress)
# Give an example name as parameter
# Ex:
# ./runExampleViaREST ControlGpioExample
# ./runExampleViaREST ListenGpioExample
#
java -Dpi4j.properties.file=./rPi4j.properties -DRESTaPI.properties.file=./RESTaPI.properties -Dlog4j.configuration=file:./log4j.xml -cp ca.magenta.pi.example/target/ca.magenta.pi.example-0.0.1-SNAPSHOT-jar-with-dependencies.jar "$@"
