#!/bin/bash
# Give an example name as parameter. Ex:
# Ex:
# ./runExampleNatively ControlGpioExample
# ./runExampleNatively ListenGpioExample
#
java -cp ca.magenta.pi.example/target/ca.magenta.pi.example-0.0.1-SNAPSHOT.jar "$@"
