#!/bin/bash
# Give an example name as parameter. Ex:
# Ex:
# ./runExampleNatively ControlGpioExample
# ./runExampleNatively ListenGpioExample
#
java -Dlog4j.configuration=file:./log4j.xml -cp ./ca.magenta.pi.example-0.0.1-SNAPSHOT-jar-with-dependencies.jar "$@"
